### ISSUE TITLE
 PullRequestInfo.Utils.jsonToRow(schema, json)

### ISSUE THREAD

**Issue by suhenhappy** [lightcopy/spark-github-pr#12]
hi,i recent learn spark and thank you the project give me some help ;but i find the project is incomplete,missing some class,eg:have not the class Uitls; 
   can you give me complete project by  email (suhenhappy@sina.com)?

**Comment by sadikovi** [comment]
Hello!

Project on GitHub is complete and has all classes to build package and use it in Spark.
Note that some classes are private to package, hence cannot be imported directly in spark-shell.

Method you are referring to is here: 
https://github.com/lightcopy/spark-github-pr/blob/master/src/main/scala/com/github/lightcopy/spark/pr/sources.scala#L145

If you want to use that in spark-shell, you could either copy code into your project, or download repository code, make class public and build it. See build instructions in README.

`sources.scala` file contains all utils that project uses to either get JSON or convert it into `InternalRow`.

Hope it helps.

**Comment by suhenhappy** [comment]
ok,i find it. tank you very much!
